/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        namaField.putClientProperty("JTextField.placeholderText", "Nama Sesuai KTP");
        noField.putClientProperty("JTextField.placeholderText", "08xxxxxxxxx");
        getRootPane().setDefaultButton(pesanButton);
    }
    
    private void tampilkanRingkasan() {

    String kelas;

    if (ekonomiRadio.isSelected()) {
        kelas = "Ekonomi";
    } else if (Bradio.isSelected()) {
        kelas = "Bisnis";
    } else {
        kelas = "Eksekutif";
    }

    List<String> fasilitas = new ArrayList<>();

    if (bagasiBox.isSelected()) {
        fasilitas.add("Bagasi");
    }

    if (makanBox.isSelected()) {
        fasilitas.add("Makan");
    }

    if (asuransiBox.isSelected()) {
        fasilitas.add("Asuransi");
    }

    String pesan = "Nama Pemesan: " + namaField.getText()
            + "\nNomor HP: " + noField.getText()
            + "\nKota Tujuan: " + kotaCombo.getSelectedItem()
            + "\nKelas: " + kelas
            + "\nFasilitas: "
            + (fasilitas.isEmpty()
                ? "-"
                : String.join(", ", fasilitas))
            + "\nCatatan: " + catatanText.getText();

    JOptionPane.showMessageDialog(
        this,
        pesan,
        "Ringkasan Pemesanan Tiket",
        JOptionPane.INFORMATION_MESSAGE
    );
}
    
    private void gantiTema(boolean gelap) {

    if (gelap) {
        FlatDarkLaf.setup();
    } else {
        FlatLightLaf.setup();
    }

    FlatLaf.updateUI();

    darkButton.setText(
        gelap ? "Mode Terang" : "Mode Gelap"
    );
}
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelasGroup = new javax.swing.ButtonGroup();
        namaField = new javax.swing.JTextField();
        noField = new javax.swing.JTextField();
        namapesan = new javax.swing.JLabel();
        hp = new javax.swing.JLabel();
        kota = new javax.swing.JLabel();
        kotaCombo = new javax.swing.JComboBox<>();
        kelasText = new javax.swing.JLabel();
        fasilitas = new javax.swing.JLabel();
        catatan = new javax.swing.JLabel();
        ekonomiRadio = new javax.swing.JRadioButton();
        eksekutifRadio = new javax.swing.JRadioButton();
        Bradio = new javax.swing.JRadioButton();
        bagasiBox = new javax.swing.JCheckBox();
        makanBox = new javax.swing.JCheckBox();
        asuransiBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatanText = new javax.swing.JTextArea();
        pesanButton = new javax.swing.JButton();
        darkButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namapesan.setText("Nama Pemesan");

        hp.setText("Nomor Hp");

        kota.setText("Kota Tujuan");

        kotaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        kelasText.setText("Kelas");

        fasilitas.setText("Fasilitas Tambahan");

        catatan.setText("Catatan");

        ekonomiRadio.setSelected(true);
        ekonomiRadio.setText("Ekonomi");

        eksekutifRadio.setText("Eksekutif");

        Bradio.setText("Bisnis");

        bagasiBox.setText("Bagasi");

        makanBox.setText("Makan");
        makanBox.addActionListener(this::makanBoxActionPerformed);

        asuransiBox.setText("Asuransi");

        catatanText.setColumns(20);
        catatanText.setRows(5);
        jScrollPane1.setViewportView(catatanText);

        pesanButton.setText("Pesan");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        darkButton.setText("Dark Mode");
        darkButton.addActionListener(this::darkButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namapesan)
                    .addComponent(kota)
                    .addComponent(hp)
                    .addComponent(catatan)
                    .addComponent(fasilitas)
                    .addComponent(kelasText))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaField)
                    .addComponent(noField)
                    .addComponent(kotaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ekonomiRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bradio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bagasiBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(makanBox)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(asuransiBox)
                                    .addComponent(eksekutifRadio)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 118, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pesanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(darkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namapesan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kota))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasText)
                    .addComponent(ekonomiRadio)
                    .addComponent(eksekutifRadio)
                    .addComponent(Bradio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fasilitas)
                    .addComponent(bagasiBox)
                    .addComponent(makanBox)
                    .addComponent(asuransiBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catatan)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(darkButton)
                    .addComponent(pesanButton))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makanBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makanBoxActionPerformed

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
        // TODO add your handling code her
    tampilkanRingkasan();
    }//GEN-LAST:event_pesanButtonActionPerformed

    private void darkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkButtonActionPerformed
        // TODO add your handling code here:
        gantiTema(darkButton.isSelected());
    }//GEN-LAST:event_darkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bradio;
    private javax.swing.JCheckBox asuransiBox;
    private javax.swing.JCheckBox bagasiBox;
    private javax.swing.JLabel catatan;
    private javax.swing.JTextArea catatanText;
    private javax.swing.JToggleButton darkButton;
    private javax.swing.JRadioButton ekonomiRadio;
    private javax.swing.JRadioButton eksekutifRadio;
    private javax.swing.JLabel fasilitas;
    private javax.swing.JLabel hp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup kelasGroup;
    private javax.swing.JLabel kelasText;
    private javax.swing.JLabel kota;
    private javax.swing.JComboBox<String> kotaCombo;
    private javax.swing.JCheckBox makanBox;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namapesan;
    private javax.swing.JTextField noField;
    private javax.swing.JButton pesanButton;
    // End of variables declaration//GEN-END:variables
}
